version: '3'
services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - '80:8080'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

